// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe8Pkl9Sl3dA5lAsbYTK8hOyrMDRt3prs',
    appId: '1:808986538905:web:ba4e579ae5e9f8601fd908',
    messagingSenderId: '808986538905',
    projectId: 'retoverse-78ff8',
    authDomain: 'retoverse-78ff8.firebaseapp.com',
    storageBucket: 'retoverse-78ff8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHc2_DwB6jSuHxO0OV7OuFqX67vCAMxZU',
    appId: '1:808986538905:android:44118fdd5f32017a1fd908',
    messagingSenderId: '808986538905',
    projectId: 'retoverse-78ff8',
    storageBucket: 'retoverse-78ff8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-zMbV3cwyMPia2w7zAaPkB-Y1y4ci5g4',
    appId: '1:808986538905:ios:72bf9b81f125f1321fd908',
    messagingSenderId: '808986538905',
    projectId: 'retoverse-78ff8',
    storageBucket: 'retoverse-78ff8.firebasestorage.app',
    iosBundleId: 'com.shindetech.retoverse',
  );
}
