name: Build and Deploy Flutter Web to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Flutter SDK
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.8" # pick your Flutter version
          channel: stable

      # Get Flutter dependencies
      - name: Install dependencies
        run: flutter pub get

      # Build Flutter for Web
      - name: Build Flutter Web
        run: flutter build web --release

      # Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_RETOVERSE_78FF8 }}
          channelId: live
          projectId: retoverse-78ff8

        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
